namespace Model.Entities.Events;

public enum EEventType {
    COMBAT,
    ACQUIRE,
    INCREASE_GOLD,
    DECREASE_RATION,
    INCREASE_COMBAT_SKILL_TEMPORARY,
    INCREASE_RATION,
    DECREASE_ENDURANCE,
    DROP_ALL_WEAPON,
    DECREASE_COMBAT_SKILL,
    DROP_WEAPON,
    DROP_BACKPACK
}