namespace Model.Entities;

public enum ESectionType
{
    TITLE_PAGE, DEDICATION, ACKNOWLEDGEMENTS, THE_STORY_SO_FAR,
    RULES_KAI_DISCIPLINES, RULES_EQUIPMENT, RULES_COMBAT, RULES_LEVELS,
    KAI_WISDOM, MAP
}